ur_rtde:
  robot_ip: "192.168.1.102"
  rtde_frequency: 500.0
  rt_receive_priority: 90
  rt_control_priority: 85
  interface_priority: 80
  linear_vel: 0.5
  linear_acc: 0.5
  servoL_lookahead_time: 0.1
  servoL_gain: 600
  robot_interface_config:
    zone_safety_mode: "SAFETY_MODE_TRUNCATE"
    incre_safety_mode: "SAFETY_MODE_STOP"
    operation_mode: "OPERATION_MODE_CARTESIAN"
    max_incre_m: 0.02
    max_incre_rad: 0.0628
    max_incre_joint_rad: 0.0628
    safe_zone: [-0.5, 0.0, -0.6, 0.0, 0.2, 0.7]

admittance_controller:
  dt: 0.002
  log_to_file: false
  enable_force_control: false
  log_file_path: "/tmp/admittance_controller.log"
  compliance6d:
    # for very soft admittance control
    # stiffness: [0, 0, 0, 0, 0, 0]
    # damping: [1.5, 1.5, 0.2, 0.1, 0.1, 0.1] # for data collection
    # inertia: [0.1, 0.1, 0.01, 0.0005, 0.0005, 0.0005]
    # for stiff position control
    stiffness: [100, 50, 1000, 0, 0, 0]
    damping: [0.5, 0.5, 6, 0.1, 0.1, 0.1] # for data collection
    inertia: [0.03, 0.03, 0.1, 0.0005, 0.0005, 0.0005]
    # for adaptive force control
    # stiffness: [0, 0, 0, 0, 0, 0]
    # damping: [1.5, 1.5, 0.5, 0.1, 0.1, 0.1] # for data collection
    # inertia: [0.1, 0.1, 0.03, 0.0005, 0.0005, 0.0005]
  max_spring_force_magnitude: 20
  direct_force_control_gains:
    P_trans: 0.5
    I_trans: 0
    D_trans: 0
    P_rot: 0.5
    I_rot: 0
    D_rot: 0
  n_af: 3
  direct_force_control_I_limit: [0, 0, 0, 0, 0, 0]

ati_netft:
  ip_address: "192.168.2.1"
  # counts per force and torque are found from 'configuration' tab in the ati web interface.
  counts_per_force: 1000000
  counts_per_torque: 1000000
  sensor_name: "netft"
  print_flag: false
  fullpath: "/tmp/netft_data.txt"
  publish_rate: 1000
  # If the force change is smaller than noise_level for more than stall_threshold frames,
  # the stream is considered dead.
  noise_level: 0.0
  stall_threshold: 100
  Foffset: [0.0, 0.0, 0.0]
  Toffset: [0.0, 0.0, 0.0]
  Gravity: [0.0, 0.0, 0.0]
  Pcom: [0.0, 0.0, 0.0]
  WrenchSafety: [80.0, 80.0, 100.0, 4, 4, 4]
  PoseSensorTool: [0, 0, -0.079, -0.9999304, 0, 0, 0.0117982]
